import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# ================= Configuration =================
CONFIG = {
    "csv_path": "outputs/outputs_kfold/cv_summary.csv",  # Summary file generated by train_cv.py
    "save_path": "outputs/outputs_kfold_plots/cv_metrics_boxplot.png",
    "metrics_to_plot": ["R2", "Pearson"],
    # MSE is usually plotted separately due to scale differences
}


def plot_paper_boxplot():
    # 1. Load data
    if not os.path.exists(CONFIG["csv_path"]):
        print(
            f"Error: File {CONFIG['csv_path']} not found. Please run train_cv.py first."
        )
        return

    df = pd.read_csv(CONFIG["csv_path"])

    # 2. Data conversion (Wide -> Long)
    # Format for seaborn
    df_melt = df.melt(
        id_vars=["fold"],
        value_vars=CONFIG["metrics_to_plot"],
        var_name="Metric",
        value_name="Score",
    )

    # 3. Set plotting style
    sns.set(style="ticks", font_scale=1.6)
    plt.rcParams["font.family"] = "sans-serif"
    plt.rcParams["font.sans-serif"] = ["Arial", "DejaVu Sans"]

    # Initialize figure
    plt.figure(figsize=(5, 4), dpi=600)

    # --- Core Plotting ---

    # A. Draw Boxplot (Base layer)
    ax = sns.boxplot(
        data=df_melt,
        x="Metric",
        y="Score",
        width=0.5,
        palette="Pastel1",
        linewidth=1.5,
        fliersize=0,
    )  # Hide outliers (handled by stripplot)

    # B. Draw Stripplot (Overlay)
    # Overlay raw data points to show distribution
    sns.stripplot(
        data=df_melt,
        x="Metric",
        y="Score",
        color=".25",
        size=6,
        alpha=0.7,
        jitter=0.15,
        linewidth=0,
        ax=ax,
    )

    # 4. Add statistics (Mean ± Std)
    means = df[CONFIG["metrics_to_plot"]].mean()
    stds = df[CONFIG["metrics_to_plot"]].std()

    # Calculate Y-axis limits for text placement
    y_max = df_melt["Score"].max()
    y_min = df_melt["Score"].min()
    y_range = y_max - y_min
    text_y_pos = y_max + y_range * 0.1

    # Annotate each metric
    for i, metric in enumerate(CONFIG["metrics_to_plot"]):
        mean_val = means[metric]
        std_val = stds[metric]

        # Format: 0.795 ± 0.012
        text = f"{mean_val:.3f}\n± {std_val:.3f}"

        plt.text(
            i,
            text_y_pos,
            text,
            ha="center",
            va="bottom",
            fontweight="bold",
            fontsize=16,
            color="black",
        )

    # 5. Adjust layout
    # Adjust Y-limit to fit text
    plt.ylim(top=text_y_pos + y_range * 0.15)

    plt.xlabel("")
    plt.ylabel("Score", fontsize=20, fontweight="bold")

    # Remove top and right spines
    sns.despine(trim=True)

    # Save plot
    os.makedirs(os.path.dirname(CONFIG["save_path"]), exist_ok=True)
    plt.tight_layout()
    plt.savefig(CONFIG["save_path"])
    print(f"[Plot] Boxplot saved to: {CONFIG['save_path']}")


if __name__ == "__main__":
    plot_paper_boxplot()
